### ISSUE TITLE
Swap the order between running and initial setup on README.md

### ISSUE THREAD

**Issue by gabriel19913** [okfn-brasil/perfil-politico#136]
I think in `README.md` the order of **running** and **initial setup** should be swapped.
When `$ docker-compose up` is runned first the API is not made available at `localhost:8000`, so I had to run `$ docker-compose run django ./manage.py migrate` and after that run `$ docker-compose up`.
Talking with other people in the chat during the sprint, they had a similar issue.

**Comment by adorilson** [comment]
And localhost:8000 must to show a "successfully" screen, not a redirect to a external site.

**Comment by giuliocc** [comment]
Fixed by: 80d3f39

\o/
