### ISSUE TITLE
[Integração de dados] Implementar live-update do comando load_bills

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/perfil-politico#181]
Para atualizar o banco de dados de produção sem perder as referências ao IDs existentes, é necessário implementar e documentar como é feita essa rotina de live-update dos projetos de lei.

## Critérios de aceite:
- [x] Verificar necessidade de adicionar novas subrotinas para update do comando load_bills, caso necessário, tê-las implementadas e testadas
- [x] Documentar procedimento para realização do update do banco no README

**Comment by arielbello** [comment]
Decidimos não implementar o live-update pois seria mais complexo para resolver, além de potencialmente muito lento sem precisar refatorar totalmente o comando `load_bills`.
Ao invés do live-update será feita a limpeza dos bills antes de carregar as novas.
