### ISSUE TITLE
[Raspador Legislativo] Corrigir spider do senado

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/perfil-politico#184]
A spider do senado do Raspador Legislativo não está funciondo. Ela deve ser corrigida para podermos atualizar os dados de bills do Perfil Político.

**Critério de aceite**
- [x] PR para corrigir a spider do senado mergeada no master do Raspador Legislativo

**Comment by arielbello** [comment]
https://github.com/cuducos/raspadorlegislativo/pull/9

**Comment by arielbello** [comment]
Aparentemente o parametro de data mudou o nome, verificar o funcionamento e fazer uma PR para corrigi-lo, caso necessário.

**Comment by arielbello** [comment]
A API continua funcionando com o parâmetro `dataInicioApresentação`, porém a spider do senado só carrega dados de um ano (envvar `START_DATE`).

**Comment by giuliocc** [comment]
Precisaria executar uma vez pra cada ano e consolidar num arquivo só então? Ou teria uma alternativa?

**Comment by arielbello** [comment]
Tem como corrigir na própria spider e fazer uma request pra cada ano, a partir do `START_DATE`. Já estou implementando.

**Comment by arielbello** [comment]
Essa PR corrige o período de extração https://github.com/cuducos/raspadorlegislativo/pull/10 , porém o endpoint que está sendo usado nessa spider (materia/pesquisa) não está mais documentado. Existe outro endpoint que aparentemente tem as mesmas informações (materia/tramitando), sendo assim, ainda pretendo fazer mais uma PR que modifique a spider para extrair os dados desse endpoint.

**Comment by arielbello** [comment]
Finalizando as alterações necessárias com essa [PR](https://github.com/cuducos/raspadorlegislativo/pull/11) que atualiza a spider do senado para usar o novo endpoint que está documentado.
