### ISSUE TITLE
[Integração de dados][spike] investigar novos dados de bens

### ISSUE THREAD

**Issue by arielbello** [okfn-brasil/perfil-politico#190]
Investigar a integração com o novo [dataset de bens de candidatos de 2022](https://dadosabertos.tse.jus.br/dataset/candidatos-2022).

## Critérios de aceite:
 - [x] Análise da integração dos novos dados de bens de candidatos realizada e documentada nesta issue
 - [x] Elaborar tarefas para atualizar o perfil político com os dados de bens de candidatos

**Comment by arielbello** [comment]
Fiz uma tabela com o mapeamento dos dados entre os dados do TSE, Eleições Brasil e Perfil Político:
https://docs.google.com/spreadsheets/d/1VFL1WZKsGEfuUPAYSAZxB9kOjGseyNcHZIQFcMz7jyc/edit#gid=456697506
A único dado que está faltando é o `detail` (`DS_BEM_CANDIDATO` no TSE), porém este não está sendo usado no front-end

**Comment by arielbello** [comment]
O dataset de bens de 2022 tem as mesmas colunas dos datasets anteriores (checado até 2014)

**Comment by arielbello** [comment]
Criada issue #192 para extrair os dados de bens de candidatos

**Comment by giuliocc** [comment]
@arielbello [copei a planilha pro drive da OKBR](https://docs.google.com/spreadsheets/d/1mHEhWe7cZj5IqrJvmufA0VzW1FqHD3lHEIVfS0IcKKA/edit?usp=sharing). Temos [novidades sobre detalhes de bens](https://twitter.com/okfnbr/status/1560351291330682882?s=20&t=c5FdzEltTGaoLSdPAWGQPw)!
