### ISSUE TITLE
[Consistência de dados] Dados de candidatos duplicados

### ISSUE THREAD

**Issue by arielbello** [okfn-brasil/perfil-politico#195]
Encontrei dados de candidatos duplicados no banco, conforme o screenshot abaixo:

![Image](https://user-images.githubusercontent.com/2393869/185457645-bf22ab60-8d44-4227-8943-e8f960d9e658.png)

**Comment by giuliocc** [comment]
Eita! Essa correção é bem prioritária, podemos colocar na sprint 8, certo?

**Comment by arielbello** [comment]
Queria entender o que pode ter causado isso. Eu acabei de rodar a mesma query no meu banco local, que só foi carregado pelo dump e parece que está tudo certo:

![Image](https://user-images.githubusercontent.com/2393869/185630668-9907d8de-549b-489c-806f-091f56e946e4.png)

**Comment by arielbello** [comment]
Investiguei junto com @giuliocc e descobrimos que os dados não estão duplicados, são de fato 3 candidaturas do Haddad, porém uma é para presidente no primeiro turno, outra para presidente no segundo turno e a última para vice-presidente da qual renunciou. No caso de Lula foi uma candidatura indeferida.
Com isso supomos que todos os dados de candidatura estejam corretos.

**Comment by arielbello** [comment]
Seguindo a investigação, vimos que a API não retorna o campo `status` (situacao_candidatura) nem o campo `round` (turno), sendo assim não é possível filtrar os políticos que não estão de fato concorrendo no primeiro turno.
Foi criada a issue #196 para adicionar esses campos na API
