### ISSUE TITLE
[Infra] Criar ambiente de staging

### ISSUE THREAD

**Issue by arielbello** [okfn-brasil/perfil-politico#199]
Criar um ambiente de staging para desenvolvimento do projeto

## Critérios de aceite
- [x] Frontend -> staging-perfil-politico.serenata.ai
- [x] Backend -> staging-api-perfil-politico.serenata.ai
- [x] Banco de dados
- [x] Configurar .env.staging
- [x] Configurar docker-compose.prod.yml

**Comment by arielbello** [comment]
Infelizmente, criar um arquivo env.staging e substituiro  `DATABASE_URL` não vai funcionar como esperado. Testei localmente e o arquivo .env parece sempre sobrescrever outros arquivos de env declarados. Existe uma issue relacionada ao problema: https://github.com/docker/compose/issues/9767
Minha solução foi colocar o `DATABASE_URL` dentro da diretiva `environment` no docker-compose.yml.
O servidor pode não ter o mesmo problema dependendo da versão do docker

**Comment by giuliocc** [comment]
@arielbello tá configurado: `https://staging-api-perfilpolitico.serenata.ai/`

\o/

Ex: `https://staging-api-perfilpolitico.serenata.ai/api/candidate/2302865/`

`https://staging-perfilpolitico.serenata.ai/` também tá configurado, mas precisa corrigir o build do projeto do frontend.

Podemos fechar?

**Comment by arielbello** [comment]
Eu acho que vale a pena fazer uma PR com esses arquivos, mesmo que eles não tenham a configuração final, mas por que já vai ficar evidente no projeto nosso fluxo de trabalho com um ambiente de staging. O que me diz?
