### ISSUE TITLE
Debug Election and Donation data

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/perfil-politico#53]
As mentioned in #42:

* `Election` model has ~3 million records
* [Donation CSV file](https://www.dropbox.com/s/io7igtet9o7a8xi/doacoes.csv.xz?dl=0) has ~7 million lines
* **However** we're able to identify and ~80 thousand donations

So I think this smells like a bug to be investigated when #42 is merged.

**Comment by rodolfolottin** [comment]
Do you have any roadmap on debugging it? I think that I can help you.

**Comment by cuducos** [comment]
> Do you have any roadmap on debugging it? I would like to help you.

No, not yet. It's been out of our radar for a while…

**Comment by cuducos** [comment]
Outdated after #88
