### ISSUE TITLE
[Suggestion] Add gender support for labels and text

### ISSUE THREAD

**Issue by anarute** [okfn-brasil/perfil-politico#93]
Since we already have the candidates gender, it would be nice to print the text accordingly or use a gender neutral approach when necessary:

![screenshot from 2018-10-01 19-46-03](https://user-images.githubusercontent.com/333447/46320140-4dce8c80-c5b3-11e8-8ae1-468499a3e2ee.png)

**Comment by cuducos** [comment]
This would be really great, @anarute! Would you mind opening this issue on [`perfil-politico-frontend`](https://github.com/okfn-brasil/perfil-politico-frontend) instead? This repo is merely the backend API, I think this is something to be implemented in the frontend. There are some [bits of code that might be helpful in this task](https://github.com/okfn-brasil/perfil-politico-frontend/blob/master/src/js/data/filters.js#L147-L148) already ; )
